services: 
  postgres:
    image: "bitnami/postgresql:latest"
    container_name: api_container
    volumes:
      - database:/bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: apitask

volumes:
 database: